name: Build and release
on: workflow_dispatch

jobs:
  build-and-release:
    name: Build and release
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.5.2

      - name: Setup Docker
        uses: docker/setup-buildx-action@v2.5.0

      - name: Build toolchain
        uses: docker/build-push-action@v4.0.0
        with:
          cache-from: type=gha
          cache-to: type=gha,mode=max
          context: ./toolchain/
          load: true
          tags: rg35xx-toolchain-new:latest

      - name: Build project
        uses: addnab/docker-run-action@v3
        with:
          image: rg35xx-toolchain-new:latest
          options: -v ${{github.workspace}}:/root/workspace
          run: make all

      - name: Create release
        run: |
          ls -a ./releases/
          echo "TODO"
